/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as landNftSol from "./landNFT.sol";
export type { landNftSol };
import type * as mapContractSol from "./mapContract.sol";
export type { mapContractSol };
export type { BuildingManager } from "./BuildingManager";
