/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ArmyDeck__factory } from "./ArmyDeck__factory";
export { IUnitNFT__factory } from "./IUnitNFT__factory";
