/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace DataTypes {
  export type CoordinatesStruct = { x: BigNumberish; y: BigNumberish };

  export type CoordinatesStructOutput = [x: bigint, y: bigint] & {
    x: bigint;
    y: bigint;
  };
}

export interface MapContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "GRID_HEIGHT"
      | "GRID_WIDTH"
      | "MAX_COORDINATE_X"
      | "MAX_COORDINATE_Y"
      | "MAX_OWNABLE_COORDINATES"
      | "MIN_COORDINATE"
      | "assignAdjacentCoordinate"
      | "assignCoordinate"
      | "assignRandomCoordinate"
      | "getAvailableAdjacentCoordinates"
      | "getCoordinateTokenId"
      | "getTokenCoordinates"
      | "isCoordinateOccupied"
      | "landNFTAddress"
      | "owner"
      | "renounceOwnership"
      | "setLandNFTAddress"
      | "totalAssignedCoordinates"
      | "transferOwnership"
      | "updateLandNFTAddress"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "GRID_HEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRID_WIDTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_COORDINATE_X",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_COORDINATE_Y",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_OWNABLE_COORDINATES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_COORDINATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assignAdjacentCoordinate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignCoordinate",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignRandomCoordinate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableAdjacentCoordinates",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCoordinateTokenId",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenCoordinates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isCoordinateOccupied",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "landNFTAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLandNFTAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssignedCoordinates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLandNFTAddress",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "GRID_HEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "GRID_WIDTH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_COORDINATE_X",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_COORDINATE_Y",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_OWNABLE_COORDINATES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_COORDINATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignAdjacentCoordinate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignCoordinate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignRandomCoordinate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableAdjacentCoordinates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCoordinateTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenCoordinates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCoordinateOccupied",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "landNFTAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLandNFTAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAssignedCoordinates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLandNFTAddress",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MapContract extends BaseContract {
  connect(runner?: ContractRunner | null): MapContract;
  waitForDeployment(): Promise<this>;

  interface: MapContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  GRID_HEIGHT: TypedContractMethod<[], [bigint], "view">;

  GRID_WIDTH: TypedContractMethod<[], [bigint], "view">;

  MAX_COORDINATE_X: TypedContractMethod<[], [bigint], "view">;

  MAX_COORDINATE_Y: TypedContractMethod<[], [bigint], "view">;

  MAX_OWNABLE_COORDINATES: TypedContractMethod<[], [bigint], "view">;

  MIN_COORDINATE: TypedContractMethod<[], [bigint], "view">;

  assignAdjacentCoordinate: TypedContractMethod<
    [tokenId: BigNumberish, existingTokenId: BigNumberish],
    [[bigint, bigint] & { x: bigint; y: bigint }],
    "nonpayable"
  >;

  assignCoordinate: TypedContractMethod<
    [tokenId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [void],
    "nonpayable"
  >;

  assignRandomCoordinate: TypedContractMethod<
    [tokenId: BigNumberish],
    [[bigint, bigint] & { x: bigint; y: bigint }],
    "nonpayable"
  >;

  getAvailableAdjacentCoordinates: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish],
    [DataTypes.CoordinatesStructOutput[]],
    "view"
  >;

  getCoordinateTokenId: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish],
    [bigint],
    "view"
  >;

  getTokenCoordinates: TypedContractMethod<
    [tokenId: BigNumberish],
    [[bigint, bigint] & { x: bigint; y: bigint }],
    "view"
  >;

  isCoordinateOccupied: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish],
    [boolean],
    "view"
  >;

  landNFTAddress: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setLandNFTAddress: TypedContractMethod<
    [_landNFTAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  totalAssignedCoordinates: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateLandNFTAddress: TypedContractMethod<
    [_newLandNFTAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "GRID_HEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GRID_WIDTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_COORDINATE_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_COORDINATE_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_OWNABLE_COORDINATES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_COORDINATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assignAdjacentCoordinate"
  ): TypedContractMethod<
    [tokenId: BigNumberish, existingTokenId: BigNumberish],
    [[bigint, bigint] & { x: bigint; y: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignCoordinate"
  ): TypedContractMethod<
    [tokenId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignRandomCoordinate"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [[bigint, bigint] & { x: bigint; y: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAvailableAdjacentCoordinates"
  ): TypedContractMethod<
    [x: BigNumberish, y: BigNumberish],
    [DataTypes.CoordinatesStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCoordinateTokenId"
  ): TypedContractMethod<[x: BigNumberish, y: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokenCoordinates"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [[bigint, bigint] & { x: bigint; y: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCoordinateOccupied"
  ): TypedContractMethod<[x: BigNumberish, y: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "landNFTAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLandNFTAddress"
  ): TypedContractMethod<[_landNFTAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAssignedCoordinates"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLandNFTAddress"
  ): TypedContractMethod<
    [_newLandNFTAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
